### PR TITLE
Refresh materialized views concurrently or with timeouts

### LINKED ISSUE #14: Refresh materialized views concurrently or with timeouts
During a refresh of an materialized view the view is locked exclusively, preventing other queries from accessing the view.

If then in turn the SQL query on the foreign database server hangs, e.g. it waits for locks, the refresh can hang potentially forever. 

Since PostgreSQL 9.4 there is an `CONCURRENTLY` option for `REFRESH MATERIALIZED VIEWS`. See [here](http://www.postgresql.org/docs/9.4/static/sql-refreshmaterializedview.html).

Adding timeouts to foreign SQL query, the refresh materialized view query, or both is another, potentially better, option.

### PR DESCRIPTION
**Pull request by fgrsnau**
This should fix #14 (but no timeout will be set for freeradius).

We should make sure that the UNIQUE constraints are fulfilled on our foreign database, too.

### CODE REVIEW

**Comment by sebschrader** [comment]
As discussed on the channel, we first need to make sure that we can guarantee uniqueness on the remote side.

**Comment by sebschrader** [comment]
Please test my work from the concurrent_refresh branch and integrate it in this PR.

**Comment by sebschrader** [comment]
Can you please reset --hard your fix-14 to my concurrent_refresh branch, so that we use my branch to close this pull request?

**Comment by fgrsnau** [comment]
I have tested the changes yesterday: The unique index `radusergroup_membership_idx` cannot be created, because some of the rows are not unique.

The problem is that the set of columns for the unique index and the columns for the `row_number()` calculation in `radusergroup` differs.

**Comment by sebschrader** [comment]
I see, my tests didn't use the real data. I'll merge this PR regardless and fix it on master.

**Pull request merged**
